# Generated by Django 4.0.2 on 2023-11-20 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100, null=True)),
                ('delay_settings', models.JSONField(default={'auto_approve': False, 'handler': None})),
                ('is_required', models.BooleanField(default=False)),
                ('default', models.CharField(max_length=500, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('value', models.JSONField(null=True)),
                ('delay', models.BooleanField(null=True)),
                ('system', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.designer')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100, null=True)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('default_string', models.CharField(max_length=500, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('default', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_time_error', models.DateTimeField(default=datetime.datetime(2023, 3, 24, 13, 21, 20, 43951))),
            ],
        ),
        migrations.CreateModel(
            name='OtherCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TablesCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=10)),
                ('max_code', models.PositiveIntegerField(null=True)),
                ('transact_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=50)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('value', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechProcessObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_code', models.IntegerField()),
                ('value', models.JSONField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.techprocess')),
                ('parent_structure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tp', to='app.techprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default={})),
                ('date_create', models.DateTimeField(null=True)),
                ('date_done', models.DateTimeField(null=True)),
                ('code', models.PositiveIntegerField()),
                ('date_delay', models.DateTimeField(null=True)),
                ('kind', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistratorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, null=True)),
                ('fact', models.CharField(max_length=100, null=True)),
                ('delay', models.JSONField(null=True)),
                ('json', models.JSONField(null=True)),
                ('json_string', models.CharField(max_length=1000, null=True)),
                ('state_income', models.CharField(max_length=100, null=True)),
                ('fact_income', models.CharField(max_length=100, null=True)),
                ('delay_income', models.JSONField(null=True)),
                ('json_income', models.JSONField(null=True)),
                ('json_string_income', models.CharField(max_length=1000, null=True)),
                ('date_update', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 15, 41, 36, 1987))),
                ('transact_id', models.CharField(max_length=25, null=True)),
                ('parent_transact_id', models.CharField(max_length=25, null=True)),
                ('json_class', models.IntegerField(null=True)),
                ('reg_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.regname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, null=True)),
                ('fact', models.CharField(max_length=100, null=True)),
                ('delay', models.CharField(max_length=100, null=True)),
                ('json', models.JSONField(null=True)),
                ('json_string', models.CharField(max_length=1000, null=True)),
                ('state_income', models.CharField(max_length=100, null=True)),
                ('fact_income', models.CharField(max_length=100, null=True)),
                ('delay_income', models.CharField(max_length=100, null=True)),
                ('json_income', models.JSONField(null=True)),
                ('json_string_income', models.CharField(max_length=1000, null=True)),
                ('date_update', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 15, 41, 36, 986))),
                ('transact_id', models.CharField(max_length=25, null=True)),
                ('parent_transact_id', models.CharField(max_length=25, null=True)),
                ('reg_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrator', to='app.regname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('delay', models.JSONField(null=True)),
                ('value', models.JSONField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_name', to='app.designer')),
                ('parent_structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_name', to='app.designer')),
            ],
        ),
        migrations.CreateModel(
            name='DictObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, null=True)),
                ('code', models.PositiveIntegerField()),
                ('parent_code', models.PositiveIntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='key_name', to='app.dictionary')),
                ('parent_structure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dict', to='app.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100, null=True)),
                ('value_str', models.CharField(max_length=1000, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default', models.CharField(max_length=500, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('value', models.JSONField(null=True)),
                ('delay', models.JSONField(null=True)),
                ('system', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='send_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('delay', models.JSONField(null=True)),
                ('value', models.JSONField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_name', to='app.contracts')),
                ('parent_structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_name', to='app.contracts')),
            ],
        ),
    ]
