# Generated by Django 4.0.2 on 2023-11-20 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techprocess',
            name='settings',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 15, 43, 16, 398472)),
        ),
        migrations.AlterField(
            model_name='registratorlog',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 15, 43, 16, 399472)),
        ),
        migrations.CreateModel(
            name='DataTypesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageConst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.JSONField(null=True)),
            ],
        ),
    ]
