# Generated by Django 4.0.2 on 2023-12-21 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_techprocess_settings_alter_registrator_date_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registratorlog',
            name='json_class',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
