# Generated by Django 4.0.2 on 2024-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_techprocess_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictobjects',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
