# Generated by Django 4.0.2 on 2024-03-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_dictobjects_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictobjects',
            name='parent_code',
        ),
    ]
