# Generated by Django 4.0.2 on 2024-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_dictobjects_parent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='settings',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='settings',
            field=models.JSONField(null=True),
        ),
    ]
