# Generated by Django 4.0.2 on 2024-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contracts_settings_designer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdrafts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tabledrafts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
