# Generated by Django 4.0.2 on 2024-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contractdrafts_active_tabledrafts_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techprocess',
            name='settings',
            field=models.JSONField(default={'system': False, 'visible': True}),
        ),
    ]
