# Generated by Django 4.0.2 on 2024-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_techprocess_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('br', models.JSONField()),
                ('lm', models.JSONField()),
                ('tr', models.JSONField(null=True)),
            ],
        ),
    ]
