# Generated by Django 4.0.2 on 2024-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_taskclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclasses',
            name='name',
            field=models.CharField(default='noname', max_length=30),
            preserve_default=False,
        ),
    ]
