# Generated by Django 4.0.2 on 2024-10-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_taskclasses_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclasses',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.taskclasses'),
        ),
    ]
