# Generated by Django 4.0.2 on 2024-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_taskclasses_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclasses',
            name='br',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='taskclasses',
            name='lm',
            field=models.JSONField(null=True),
        ),
    ]
