# Generated by Django 4.0.2 on 2024-10-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_taskclasses_br_alter_taskclasses_lm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclasses',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
