# Generated by Django 4.0.2 on 2024-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_taskclasses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsTransactIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=10)),
                ('code', models.PositiveIntegerField()),
                ('last_transact_id', models.BigIntegerField()),
            ],
        ),
    ]
