# Generated by Django 4.0.2 on 2024-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_objectstransactids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arhiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField()),
                ('transact_id', models.CharField(max_length=25)),
                ('parent_transact', models.CharField(max_length=25)),
                ('date_update', models.DateTimeField()),
                ('class_id', models.IntegerField()),
                ('code', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=20)),
                ('header_id', models.IntegerField(null=True)),
                ('value_inc', models.JSONField(null=True)),
                ('value_outc', models.JSONField(null=True)),
            ],
        ),
    ]
