# Generated by Django 4.0.2 on 2024-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_arhiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhiv',
            name='parent_transact',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
