# Generated by Django 4.0.2 on 2024-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_arhiv_parent_transact'),
    ]

    operations = [
        migrations.AddField(
            model_name='arhiv',
            name='user_id',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
