# Generated by Django 4.0.2 on 2024-11-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_usersets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registratorlog',
            old_name='state',
            new_name='date_delay',
        ),
    ]
