# Generated by Django 4.0.2 on 2024-11-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_state_registratorlog_date_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registratorlog',
            name='date_delay',
            field=models.DateTimeField(null=True),
        ),
    ]
