# Generated by Django 4.0.2 on 2024-12-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_registratorlog_date_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registratorlog',
            name='date_update',
            field=models.DateTimeField(db_index=True),
        ),
    ]
